name: DialogFlowPlugin
main: com.github.freddyyj.dialogflow.Core
version: 0.2.0
author: FreddyYJ_
commands:
    df:
        usage: "/df [Command]"
        description: Default command for use this plugin.
        permission: dialogflow.df
    dialogflow:
        usage: "/dialogflow [Command]"
        description: Default command.
        permission: dialogflow.df
permissions:
    dialogflow.df:
        description: Allow to look command list.
        default: true
    dialogflow.chat:
        description: Allow to chat with DialogFlow.
        default: true
    dialogflow.send:
        description: Allow to send request to DialogFlow once.
        default: true
    dialogflow.language:
        description: Allow to look language list for current Agent.
        default: true
    dialogflow.list:
        description: Allow to look Agent list.
        default: true
    dialogflow.*:
        description: Allow all permissions.
        default: op
        children:
            dialogflow.df: true
            dialogflow.chat: true
            dialogflow.send: true
            dialogflow.language: true
            dialogflow.list: true