name: DialogFlowPlugin
main: com.github.freddyyj.dialogflow.Core
version: 0.0.1
author: FreddyYJ_
commands:
    df:
        usage: "/df [Command]"
        description: Default command for use this plugin.
    dialogflow:
        usage: "/dialogflow [Command]"
        description: Default command.