name: DialogFlowPlugin
main: com.github.freddyyj.dialogflow.Core
version: 0.0.1
author: FreddyYJ_
commands:
    df:
        usage: "/df [Command]"
        description: Default command for use this plugin.
    dialogflow:
        usage: "/dialogflow [Command]"
        description: Default command.
    start:
        usage: "/df start"
        description: Start chatting with DialogFlow.
    dfstop:
        usage: "/df stop"
        description: Stop chatting with DialogFlow.
    send:
        usage: "/df send <Message> [LanguageCode]"
        description: Send message with language code to DialogFlow.
    langlist:
        usage: "/df language"
        description: List of language of current Agent.
    list:
        usage: "/df list"
        description: List of player who current chatting.